### ISSUE TITLE
Crash using char, bad size if using short

### ISSUE THREAD

**Issue by aubreyrjones** [llvm-dcpu16/llvm-dcpu16#121] opened 2012-04-14 17:41 UTC
Here's some code:

```
void copy_words(word_t *dest, word_t *source, word_t size){
    for (; size; size--){
        *dest = *source;
        ++dest;
        ++source;
    }
}
```

If I use

```
typedef unsigned short word_t;
```

I get bad assembly code that thinks sizeof(short) == 2. Upon reflection, that's to be expected. How is C to know that suddenly shorts are the only addressable unit?

But if I rewrite with char, or use the following typedef:

```
typedef char word_t;
```

I get the following crash:

```
clang -I include -ccc-host-triple dcpu16 -S src/memory.c -o test_bin/memory.s
clang-3.1: /home/netzapper/dcpu16/llvm-dcpu16/lib/CodeGen/SelectionDAG/LegalizeDAG.cpp:1318: void<unnamed>::SelectionDAGLegalize::LegalizeOp(llvm::SDNode*): Assertion `TLI.isTypeLegal(StVT) && "Do not know how to expand this store!"' failed.
Stack dump:
0.  Program arguments: /home/netzapper/dcpu16/llvm-dcpu16/cbuild/bin/clang-3.1 -cc1 -triple dcpu16 -S -disable-free -main-file-name memory.c -mrelocation-model static -mdisable-fp-elim -mconstructor-aliases -momit-leaf-frame-pointer -coverage-file test_bin/memory.s -resource-dir /home/netzapper/dcpu16/llvm-dcpu16/cbuild/bin/../lib/clang/3.1 -I include -fmodule-cache-path /var/tmp/clang-module-cache -fno-dwarf-directory-asm -fdebug-compilation-dir /home/netzapper/dcpu16/nos/nos_modules -ferror-limit 19 -fmessage-length 179 -mstackrealign -fgnu-runtime -fobjc-runtime-has-arc -fobjc-runtime-has-weak -fobjc-fragile-abi -fdiagnostics-show-option -fcolor-diagnostics -o test_bin/memory.s -x c src/memory.c 
1.  <eof> parser at end of file
2.  Code generation
3.  Running pass 'Function Pass Manager' on module 'src/memory.c'.
4.  Running pass 'DCPU16 DAG->DAG Pattern Instruction Selection' on function '@copy_words'
clang-3: error: unable to execute command: Aborted
clang-3: error: clang frontend command failed due to signal (use -v to see invocation)
clang-3: note: diagnostic msg: Please submit a bug report to  and include command line arguments and all diagnostic information.
clang-3: note: diagnostic msg: Preprocessed source(s) and associated run script(s) are located at:
clang-3: note: diagnostic msg: /tmp/memory-0xxenK.i
clang-3: note: diagnostic msg: /tmp/memory-0xxenK.sh
make: *** [test_memory] Error 254
```

**Comment by ghost** [comment] 2012-04-14 18:04
Duplicate of issue #117 .

> I get bad assembly code that thinks sizeof(short) == 2. Upon reflection, that's to be expected. How is C to know
> that suddenly shorts are the only addressable unit?

Because we can (and have) told clang/llvm with the target definition that. We can't use chars yet, since we haven't get zero/sign extend and trunc store working yet. Mainly because we wait for notch to include arithmetic operations, so that we can do sign shifts etc.

Update:
Byte / Char == 8 bit (but will always be aligned to 16 bit and is more computing expensive then using native shorts/ints)
Short == Int == 16 bit
Long == 32 bit
Long Long == 64 bit

**Comment by krasin** [comment] 2012-04-14 18:34
The crash is possibly #117.

I will take a look if we can fix things like p++, where p is a pointer to short.

**Comment by aubreyrjones** [comment] 2012-04-14 19:55
@arbaal does your update imply that sizeof(char) == sizeof(short) == 1?

**Comment by ghost** [comment] 2012-04-14 20:10
No, shorts are 2 bytes. Bytes will be 1 byte, but since you can't save them anywhere with the size of 1, since we have word only addresses and our regs/stack is 16bit aligned, you can't save them practically without loosing 8 bits. Of course you could do shifting/bit masking etc, but still: 8 bit operations will be very expensive, since we need to do extra sign/zero extension etc.

**Comment by aubreyrjones** [comment] 2012-04-14 21:02
I don't see how this makes any kind of sense.

You can only address by word. Period.

It is going to cause extensive pain and suffering if code like this allocates 2 words of memory:

```
uint16_t *word_ptr = malloc(sizeof(uint16_t));
```

Now, I'm 100% okay with a char being 16 bits, sizeof(char) == 1, sizeof(short) == 2, char is the native data type (shorts are actually 32 bits wide). I am also 100% okay with sizeof(char) == 1, sizeof(short) == 1, and 8-bit types are merely treated differently in software.

But what isn't okay is that my only choices are an 8-bit type emulated in software, or an unsigned short that takes up twice as much memory as it needs to.  It has to be made consistent.

**Comment by krasin** [comment] 2012-04-14 22:10
Let's wait for the spec updates. Word-addressable memory is a very awkward feature of DCPU-16 and it might go. If so, all problems are gone.

**Comment by aubreyrjones** [comment] 2012-04-14 23:42
Wait, are you expecting that Notch will change the spec so that the distance between address 0x01 and 0x02 is 8 bits instead of the current 16? That won't happen. That is precisely the sort of complexity that the DCPU16 clearly avoids by design. Also, I can guarantee you that memory for the DCPU is "char[] ram = new char[0x1000];" in Java (it is the only unsigned type). Handling read from odd offset would complicate a _lot_ of code for him, and switching to a longer type (int) would require him to manually emulate unsigned math. It's not impossible, but it'd be far more annoying than simply adding the signed shift and signed arithmetic instructions that people have asked for.

So, I take for granted that the addressable unit will always be 16-bits.

That should be the size of char. Think of DCPU16 as a machine with native wchar_t bytes. It really does address 0x10000 _bytes_ of memory, it is just that each byte is 16 bits wide. Or perhaps think of it as one of those old weird machines from the 70's with, like, 88-bit words and 11-bit bytes.

Do not emulate 8-bit bytes. They are unnecessary in this situation. Entirely. They will require expensive emulation at every turn in order to ensure they don't overflow or in some other way deviate from the spec. And why? I mean really, _why_ if an 8-bit number is more expensive than a 16-bit number in cycles, and costs the same in aligned memory, why would you use it?

There is _no_ advantage to them. There is no existing ascii systems software to interface to. There is no business requirement that we Leverage Our Existing Assets. There's no libc already written for this machine, and even the likely candidates (avr libc) are too heavyweight to be used without substantial porting. There is _no reason_ that an 8-bit type is necessary. Even text output, as shown so far, is based on 16-bit character.

Please simply make 

```
CHAR_BITS = 16
sizeof(char) == sizeof(short) == sizeof(int) == 1;
sizeof(long) == 2;
```

Instead of trying to complicate the design to emulate what we do for a living, just accept that there is only one size of memory transaction here. Embrace the simplicity. Write the entire backend around that one, basic type. It's all bytes. It's all chars. They're just 16 bits wide.

**Comment by ghost** [comment] 2012-04-15 08:41
@netzapper Since LLVM/Clang are hardcoded at some places to assume that CHAR_BIT = 8, we hesitate right now to make such an deep change. You can try to make a branch and fix the CHAR_BIT for yourself and test how well/bad it goes. I might have time to try that next weekend myself.

**Comment by ghost** [comment] 2012-04-15 09:56
Okay, just tried it out how "easy" it is. When you changed the hard coded values for the char width and align, and fix one assert, you must "only" change LLVM to handle the new align values correctly (because he would otherwise downgrade i16 align 1 values to i8 values ...).

Here is a diff from another guy who fixed the problem himself, but contains some other junk:
http://clang-developers.42468.n3.nabble.com/attachment/777776/0/llvm-clang.r102726.diff

Update:
I tried it a little more. If you just fix the hard coded clang parts, llc won't compile llvm IR anymore and will stay in an infinity loop. I tried to debug it, but there seems no "easy quick hack" for this problem.

**Comment by aubreyrjones** [comment] 2012-04-15 17:19
That sucks multiple monkeys' balls simultaneously.

I didn't mean to imply it was a trivial change. But, I didn't think it would be that bad. Sorry.

Umm... so, I'm not committing to anything, because I kind of loathe hacking huge C++ projects, and I've literally never looked at clang/llvm before. But, where might I look for these parts where the charsize is hardcoded and the char is defined? And what am I looking for? A unique-ish token or two would be super helpful to orient me.

**Comment by ghost** [comment] 2012-04-15 17:36
You will find DCPU's target configuration in the llvm/lib/Target/DCPU16 folder. There is a file called DCPU16ISelLowering.cpp which contains the Function Allignment code:   s

```
setMinFunctionAlignment(2);
setPrefFunctionAlignment(2);
```

Then you have the hard coded part from clang in following files:

clang/include/clang/Basic/TargetInfo.h

```
  unsigned getCharWidth() const { return 8; } // FIXME
  unsigned getCharAlign() const { return 8; } // FIXME

  /// getShortWidth/Align - Return the size of 'signed short' and
  /// 'unsigned short' for this target, in bits.
  unsigned getShortWidth() const { return 16; } // FIXME
  unsigned getShortAlign() const { return 16; } // FIXME
```

clang/lib/Basic/TargetInfo.cpp defines the default values (which would need to be changed)

clang/lib/Basic/Targets.cpp defines the different targets and which datatypes they use/define (DCPU16TargetInfo).

clang/lib/Headers/limits.h defines CHAR_BITS for clang.

You could also search the LLVM tree for "char_bit" or "alignment" for more information/hard coded stuff.

**Comment by ghost** [comment] 2012-04-15 17:39
Non the less: I will wait for notch to update the specs to a more final conclusion, till I will try to fix the addressing issue for now.

**Comment by aubreyrjones** [comment] 2012-04-16 02:15
Could we fix this in the short term by having the AsmWriter output some sort of tags on address offsets?

For instance, can it be patched to emit something like:

```
  .align 2
:three_words
  .word 0x00
  .word 0x01
  .word 0x02
:ex
  set a, [0Bx02 + three_words] ; reference to the second word
  set b, [0Bx04 + three_words] ; reference to the third word
```

Then nos_link could detect '0Bx' literals and divide them by 2 to get word offsets.

Of course, maybe by the time that the assembly's being written, it isn't clear if it's a label+offset or just a number.

Actually, maybe the bigger problem is not labels but registers... damn.

**Comment by ghost** [comment] 2012-04-16 04:42
We already convert the byte-based addresses and offset! 
Look at 7f22dff321d1bd6f9c158045b5876c825bae6f98 and 935d14999d96c7f823fc233244b49078fff32d76 . Our problem right now is, that we can't handle char (8-bit) variables AND that a "sizeof()" will print the size in byte and not words.

What we need now is an update spec from notch with arithmetic.

**Comment by krasin** [comment] 2012-04-16 04:45
I also have a suspicion that

``` C
int* p = a;
p++;
return *p;
```

will return incorrect results.

**Comment by ghost** [comment] 2012-04-16 07:13
I think that will work fine, since p++ just adds 1 to the pointer address, which is at run time word based and valid. Sizeof() is uterly broken thought and will make a lot of troubles when you want to implement malloc() (Which should be word based in my eyes).

**Comment by ghost** [comment] 2012-04-16 09:16
I see right now 3 possibilities:
1. We define BYTES/CHAR in Clang to be 16-bit and fix all LLVM code that keeps crashing.
2. We don't touch clangs/llvm's 8-bit Byte, but "cheat" our way out, by handling all i8 as i16 and fixing the sizeof() operator.
3. We support i8 fully, don't touch clang/llvm 8-bit byte and fix the sizeof() operator.

The first would be the cleanest, whereas the second the fastes and still "somewhat clean" for the end user.

**Comment by aubreyrjones** [comment] 2012-04-16 13:32
My preference for number (1) is determined almost entirely by whether or not we could get the variable bytesize patch into the upstream source. I don't want to hack that deep into all of that code only to have them break it on us because they didn't even know we made a fix.

(2) is basically my original suggestion (hack on 'short' until it works).

I don't like (3). There's never a situation on dcpu16 where 8-bit datatype actually makes sense.

(Unrelated, @arbaal, you want me to fix nos_link so it accepts signed offsets? You mention something in llvm-dcpu16/llvm-dcpu16@935d14999d96c7f823fc233244b49078fff32d76 that maybe assemblers should be "influenced" to accept it.)

**Comment by ghost** [comment] 2012-04-16 14:15
Wait a second ... I think I found a way for (1) but that needs some more research/try out. Basically it's based on the assumption that the changed to clang are sufficient, we let LLVM do it's own way and just rewrite the offsets/addresses.

@netzapper Yeah, the support for signed offests would be nice.

**Comment by Blei** [comment] 2012-04-16 15:05
That (i.e. rewriting offsets) won't work, the code that @krasin wrote as example actually produces a `ADD A, 0x2` at the moment.

**Comment by ghost** [comment] 2012-04-16 15:32
Yeah, I see right now. It would do a "%incdec.ptr = getelementptr inbounds i16\* %1, i32 1", which will use the byte based addressing. _mhh_

I have wrote a patch who handles everything well, EXCEPT this problem (pushed into my repos). So we need to fix that problem now .... _mhh_ ....

BTW: clang handles word based addressing very well.

**Comment by ghost** [comment] 2012-04-16 15:52
Okay, the class which defines that instruction is GetElementPtrInst and is located in llvm/include/Instructions.h and looks, nice...

**Comment by ghost** [comment] 2012-04-16 17:19
I think it would be best to "hack" the llvm/include/Target/TargetData.h to return word based sizes ... but I think THEN hell will break loose.

**Comment by krasin** [comment] 2012-04-16 17:49
Another idea is to pretend that word is i8. In this case, everything but integer limits will be fine, but I'm not aware if LLVM uses these limits in any place

**Comment by krasin** [comment] 2012-04-16 17:57
To clarify a little bit. Currently, we have

```
target datalayout = "e-p:16:16:16-i8:16:16-i16:16:16-i32:16:32-s0:16:16-n16"
```

The idea is to have

```
target datalayout = "e-p:8:8:8-i8:8:8-i16:8:16-i32:8:32-s0:8:8-n8"
```

or something like that.

**Comment by krasin** [comment] 2012-04-16 17:58
Also, I believe that this is a very bad hack and I only put it here for the reference. I don't have my vote for it.

**Comment by ghost** [comment] 2012-04-16 18:43
Okay, I will open a PR for review, which is also a hack, but not _that_ intrusive (But still a bad workaround). Pointer arithmetic is still working, sizeof() is word based and the smallest possible value is 16bit big.

**Comment by aubreyrjones** [comment] 2012-04-16 18:48
@arbaal Could you drop by netzapper/nos_link#2 and leave a comment describing the syntax you'd prefer. I don't know if you want, for instance, negative hex numbers and whatnot.

**Comment by ghost** [comment] 2012-04-17 05:24
@netzapper  Update clang/llvm to the newest trunk, and your example should work. If your output looks a little weired, always try to use -O1 or even -O2 to see if the optimizer can kick in.

**Comment by ghost** [comment] 2012-04-21 18:34
This issue is fixed by now, since we introduced basic wide char support.

**Closed as completed by ghost** 2012-04-21 18:34 UTC
Labels: duplicate
